
import { Metadata } from "next"
import Link from "next/link"


export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevaluation",
    template: "%s | Codevalution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{     
            padding: '0', 
            margin: '0',
            backgroundColor: "#444",
            color: 'gray'
        }}>
        <header
          style={{     
            backgroundColor: 'lightblue',
            padding: '10px 20px',
        }}
        >
          <p>Header</p>
          <Link style={{textDecoration: 'none',color: "orange",fontSize: "16px",fontFamily: "sans-serif",fontWeight: "bolder",borderBottom: '2px solid orange',paddingBottom: '3px', margin: '20px',}} href={'/'}>
          Home </Link>
          <Link 
          style={{textDecoration: 'none',color: "darkcyan",fontSize: "16px",fontFamily: "sans-serif",fontWeight: "bolder",borderBottom: '2px solid snow',paddingBottom: '3px',}} 
          href={'/blog'}> Blog </Link>
          <Link href={'/products'}> Products </Link>
          <Link href={'/profile'}> Profile </Link>
        </header>
        {children}
        <footer
        style={{     
          backgroundColor: 'lightgray',
          padding: '10px 20px',
          textAlign: 'center',
          color: 'indigo',
          marginTop: '17rem',  
      }}
        >
          <h1>Footer</h1>  
        </footer>
      </body>
    </html>
  )
}
