
import { Metadata } from "next"
import Link from "next/link"


export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevaluation",
    template: "%s | Codevalution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "lightgray", margin: 0}}>
        <header style={{backgroundColor: "darkcyan", padding: "15px"}}>
          <span style={{fontSize: "20px", color: "orange", padding: "0 20px"}}>
             ⟨ Header ⟩
          </span>
          <Link href={'/'}> Home </Link>
          <Link href={'/blog'}> Blog </Link>
          <Link href={'/products'}> Products </Link>
          <Link href={'/profile'}> Profile </Link>
          <Link href={'/complex-dashboard'}> Dashboard </Link>
        </header>
        {children}
        <footer style={{ backgroundColor: "darkcyan", padding: "0 20px"}}>
          <h1> ⟨ Footer ⟩ </h1>  
        </footer>
      </body>
    </html>
  )
}
