import { Metadata } from "next"


export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevaluation",
    template: "%s | Codevalution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{     
            padding: '0', 
            margin: '0',
            backgroundColor: "#444",
            color: 'gray'
        }}>
        <header
          style={{     
            backgroundColor: 'lightblue',
            padding: '10px 20px',
        }}
        >
          <p>Header</p>
          
        </header>
        {children}
        <footer
        style={{     
          backgroundColor: 'lightgray',
          padding: '10px 20px',
          textAlign: 'center',
          color: 'indigo',
          marginTop: '17rem',  
      }}
        >
          <h1>Footer</h1>  
        </footer>
      </body>
    </html>
  )
}
